version: '3'

services:
# Database using MY SQL
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: demodb
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    ports:
      - 3306:3306
    volumes:
     - demodbData:/var/lib/mysql
    networks:
     - backendNetwork
# API Services using Spring Boot 2+   
  api:
    image: openjdk:10-jre-slim
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - ./api/target/api-0.0.1-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backendNetwork
      - frontendNetwork
 # UI - Frontend using Angualr 8+  
  ui:
    image: nginx:alpine
    container_name: ui
    ports: 
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ui-ant/dist/ui-ant/:/usr/share/nginx/html
    networks:
      - frontendNetwork
    

volumes:
  demodbData:
  
networks:
  backendNetwork:
  frontendNetwork: